# Canonical config for the dev environment. COMMITTED on purpose - every value
# here is non-secret (hostnames, instance sizes, a public pubkey), and CI needs
# the same values a local apply uses. Without a committed var file, a CI apply
# would fall back to variable defaults, see domain_name = "" and tear down the
# TLS listener and DNS records.
#
# Local:  terraform apply -var-file=dev.tfvars
# CI:     same, plus -var aws_profile= -var relay_image=<immutable sha tag>
#
# Secrets never live here. The RDS password is generated by Terraform, and the
# relay identity key is set out-of-band (see secrets.tf).

aws_region = "eu-west-3"

# Overridden to "" in CI, where credentials come from OIDC rather than a profile.
aws_profile = "alc-tf"

project_name = "buzz"
environment  = "dev"

# ── DNS / TLS ────────────────────────────────────────────────────────────────
domain_name     = "bitcoinmarkets.app"
relay_subdomain = "relay" # -> relay.bitcoinmarkets.app

# ── Relay ────────────────────────────────────────────────────────────────────
# CI overrides this with ghcr.io/adrienlacombe/buzz:sha-<7> so the running task
# definition records exactly which commit is deployed. The :main default is only
# for a manual local apply.
relay_image = "ghcr.io/adrienlacombe/buzz:main"

relay_cpu           = 512  # 0.5 vCPU
relay_memory        = 1024 # MiB
relay_desired_count = 1

# Hex Nostr pubkey (64 chars) granted relay-owner rights. Public value.
# Required before require_relay_membership can be enabled - the relay exits at
# startup with membership required and no owner (main.rs:228). Convert an npub
# to hex first; a plan-time validation rejects anything that is not 64-hex.
owner_pubkey = ""

# Restricts the relay to pubkeys in its membership table, so NIP-42 auth alone is
# not enough to use it. Still false because it needs owner_pubkey above; flipping
# it without one fails at plan time rather than crash-looping the service.
require_relay_membership = false

# Browser repo UI at https://relay.bitcoinmarkets.app/repos. The web assets are
# already in the image, so this only enables the route.
serve_git_web_gui = true

# ── NIP-SW Starknet wallet bindings ──────────────────────────────────────────
# Endpoint the relay calls to verify kind:30178 attestations at ingest. Public
# node, no API key, so it belongs in this committed file. Verified live:
# starknet_chainId returns 0x534e5f4d41494e, i.e. genuinely mainnet.
#
# Verification fails closed — blank here means every SN_MAIN binding is rejected
# rather than stored unverified.
starknet_rpc_sn_main = "https://mainnet.nodes.starknet.org/rpc/v0_10"

log_level          = "buzz_relay=info,buzz_db=info,buzz_auth=info,tower_http=warn"
log_retention_days = 14

# ── Postgres ─────────────────────────────────────────────────────────────────
db_engine_version        = "17.10"
db_instance_class        = "db.t4g.micro"
db_allocated_storage     = 20
db_max_allocated_storage = 100
db_multi_az              = false
db_backup_retention_days = 7

# ── Redis ────────────────────────────────────────────────────────────────────
redis_engine_version = "7.1"
redis_node_type      = "cache.t4g.micro"

# ── CI/CD ────────────────────────────────────────────────────────────────────
github_repository    = "adrienlacombe/buzz"
github_deploy_branch = "main"

# ── Lifecycle ────────────────────────────────────────────────────────────────
# RDS, EFS and the media bucket additionally carry prevent_destroy in their
# resource blocks, which is what actually protects them from an unattended CI
# apply. These three only affect a deliberate local teardown.
deletion_protection        = false
skip_final_snapshot        = true
force_destroy_media_bucket = false
