# Canonical config for the dev environment. COMMITTED on purpose - every value
# here is non-secret (hostnames, instance sizes, a public pubkey), and CI needs
# the same values a local apply uses. Without a committed var file, a CI apply
# would fall back to variable defaults, see domain_name = "" and tear down the
# TLS listener and DNS records.
#
# Local:  terraform apply -var-file=dev.tfvars
# CI:     same, plus -var aws_profile= -var relay_image=<immutable sha tag>
#
# Secrets never live here. The RDS password is generated by Terraform, and the
# relay identity key is set out-of-band (see secrets.tf).

aws_region = "eu-west-3"

# Overridden to "" in CI, where credentials come from OIDC rather than a profile.
aws_profile = "alc-tf"

project_name = "buzz"
environment  = "dev"

# ── DNS / TLS ────────────────────────────────────────────────────────────────
domain_name     = "bitcoinmarkets.app"
relay_subdomain = "relay" # -> relay.bitcoinmarkets.app

# ── Relay ────────────────────────────────────────────────────────────────────
# relay_image is deliberately ABSENT here, and has no default in variables.tf.
#
# CD owns it: deploy-aws.yml passes the commit's immutable
# ghcr.io/adrienlacombe/buzz:sha-<7> tag. When this file pinned :main instead,
# every local apply silently rewrote the image field and reverted whatever CD had
# just deployed — a second writer to a field CD already owns.
#
# So a local apply must state which image it means. To keep what is deployed:
#
#   terraform apply -var-file=dev.tfvars -var relay_image="$(
#     aws ecs describe-task-definition --task-definition buzz-dev-relay \
#       --profile alc-tf --region eu-west-3 \
#       --query 'taskDefinition.containerDefinitions[0].image' --output text)"

relay_cpu           = 512  # 0.5 vCPU
relay_memory        = 1024 # MiB
relay_desired_count = 1

# Hex Nostr pubkey (64 chars) granted relay-owner rights. Public value.
# Required before require_relay_membership can be enabled - the relay exits at
# startup with membership required and no owner (main.rs:228). Convert an npub
# to hex first; a plan-time validation rejects anything that is not 64-hex.
owner_pubkey = "d29f26f8d3216498c5ded281edb884e33da465a4a4614ffc3bcd92db4983b3e5"

# FALSE on purpose: this relay is public. Anyone may join with their own key, or
# let Buzz generate one (desktop does this automatically on first run --
# app_state.rs:343 keyring -> identity.key -> generate + save).
#
# Turning this on would gate *all* access on the membership table, which is the
# opposite of a public relay. It does NOT control who can grant admin -- that is
# enforced independently in the relay and needs no configuration:
#
#   kind:9032 role change   "Only owners may change roles" (relay_admin.rs:369)
#   setting role = owner    blocked outright; transfer only via RELAY_OWNER_PUBKEY
#   adding an admin member  requires owner (relay_admin.rs:273)
#   admins removing people  members only, never admins or the owner
#   invite links            DB CHECK pins role = 'member' (migration 0025)
#   non-members             sender_role falls back to "" and fails every check
#
# So owner_pubkey above is the whole admin story: only that key can create admins,
# whether membership enforcement is on or off.
require_relay_membership = false

# Browser repo UI at https://relay.bitcoinmarkets.app/repos. The web assets are
# already in the image, so this only enables the route.
serve_git_web_gui = true

# ── Starknet ─────────────────────────────────────────────────────────────────
# Public node, no API key, so it belongs in this committed file. Verified live:
# starknet_chainId returns 0x534e5f4d41494e, i.e. genuinely mainnet. Note the
# hostname ordering: nodes.starknet.org, not starknet.nodes.org.
#
# Previously fed the relay for NIP-SW verification; now consumed by buzz-paymaster.
starknet_rpc_url = "https://mainnet.nodes.starknet.org/rpc/v0_10"

# ── Sponsorship (buzz-paymaster) ─────────────────────────────────────────────
# Disabled, and `paymaster_enabled = false` means **no resources at all** — not
# "resources with zero tasks". That distinction was learned by breaking it: the first
# version created the IAM roles and task definition unconditionally, and the next CI
# deploy failed on iam:PassRole for a role the bootstrap stack had not yet been told
# about. A relay deploy was blocked by an optional service that was meant to be off.
#
# Turning it on, in this order:
#
#   1. Apply bootstrap/ — separate state, CI never touches it. Grants iam:PassRole on
#      the paymaster roles and denies the deploy role any read of the sponsor's key:
#        terraform -chdir=infra/aws/bootstrap apply
#   2. Fund a Starknet account for the sponsor to spend from.
#   3. Write its address and signing key, plus a Nostr identity, to the
#      buzz-dev/paymaster secret out-of-band (command in paymaster.tf).
#   4. Deploy one NostrAccount and confirm it lands at the address
#      `buzz wallet address` derives — this verifies the UDC deploy_from_zero
#      assumption before the sponsor starts deploying accounts for other people.
#   5. Set the three values below.
#
# Step 1 before step 5, or you reproduce the failure above.
paymaster_enabled       = false
paymaster_desired_count = 0
# paymaster_account_class_hash = "0x0414f62ea1ed35f8c7bd3b794d94efc95e01bccf04e0f47211fc198f7f56f537"

# ── Markets indexer (@the-situation/indexer) ─────────────────────────────────
# Disabled. indexer_enabled = false means **no resources on the create path** —
# same lesson as paymaster: half-adding IAM roles without bootstrap PassRole
# breaks relay CD.
#
# Once enabled, setting indexer_enabled = false fails plan (EFS prevent_destroy)
# so CD cannot wipe the markets SQLite. That is intentional. To disable after
# enable: terraform state rm 'aws_efs_file_system.indexer[0]' first (and accept
# losing the count-gated resources). Not a silent destroy of an existing DB.
#
# After the first GHCR push, make ghcr.io/adrienlacombe/the-situation-sdk/indexer
# public (Packages → Change visibility) so ECS can pull without a registry secret.
#
# Turning it on, in this order (Adrien applies AWS after the PR merges):
#
#   1. terraform -chdir=infra/aws/bootstrap apply
#      (PassRole on indexer roles + GetSecretValue Deny on buzz-dev/indexer)
#   2. Set indexer_enabled = true, indexer_desired_count = 0, and an immutable
#      indexer_image pin (creates secret/roles/TG without starting a task):
#        indexer_image = "ghcr.io/adrienlacombe/the-situation-sdk/indexer:0.19.1@sha256:c41cf55281c2060e306d05feb108b1867473edf4dac11a223251b2fc5e0bc596"
#      (also tagged :sha-94279a1). Rejects :main / :latest. Do NOT reuse relay_image.
#   3. put-secret-value ADMIN_API_KEY + VOYAGER_API_KEY (keys only in docs —
#      see indexer.tf / README). Never commit values.
#   4. Set indexer_desired_count = 1 and apply again (indexer service does NOT
#      ignore_changes desired_count — unlike paymaster — so this apply works).
#   5. POST /admin/markets for the v1 market (payload in README).
#   6. Wallet INDEXER_URL = https://markets.bitcoinmarkets.app
#
# ACM already gains a markets.bitcoinmarkets.app SAN with this PR (shared cert).
# Route53 A alias + ALB host-header rule appear only when enabled.
indexer_enabled       = false
indexer_desired_count = 0
# indexer_image = "ghcr.io/adrienlacombe/the-situation-sdk/indexer:0.19.1@sha256:c41cf55281c2060e306d05feb108b1867473edf4dac11a223251b2fc5e0bc596"

log_level          = "buzz_relay=info,buzz_db=info,buzz_auth=info,tower_http=warn"
log_retention_days = 14

# ── Postgres ─────────────────────────────────────────────────────────────────
db_engine_version        = "17.10"
db_instance_class        = "db.t4g.micro"
db_allocated_storage     = 20
db_max_allocated_storage = 100
db_multi_az              = false
db_backup_retention_days = 7

# ── Redis ────────────────────────────────────────────────────────────────────
redis_engine_version = "7.1"
redis_node_type      = "cache.t4g.micro"

# ── Lifecycle ────────────────────────────────────────────────────────────────
# RDS, EFS and the media bucket additionally carry prevent_destroy in their
# resource blocks, which is what actually protects them from an unattended CI
# apply. These three only affect a deliberate local teardown.
deletion_protection        = false
skip_final_snapshot        = true
force_destroy_media_bucket = false
